-- =============================================================================
-- Company Portal — Supabase schema
-- ใช้ Auth0 เป็น Identity Provider ผ่าน Supabase "Third-Party Auth"
-- ก่อนรันไฟล์นี้: Authentication → Sign In / Providers → Third Party Auth → Auth0
-- =============================================================================
-- รันไฟล์นี้ทั้งไฟล์ใน SQL Editor ได้เลย (idempotent — รันซ้ำได้)
-- =============================================================================

create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- Helper: ดึง Auth0 subject (user id) จาก JWT ที่แนบมากับ request
-- -----------------------------------------------------------------------------
create or replace function public.auth0_sub()
returns text
language sql
stable
as $$
  select nullif(auth.jwt() ->> 'sub', '');
$$;

comment on function public.auth0_sub() is 'Auth0 user id (sub) ของ request ปัจจุบัน — null ถ้าไม่ได้ล็อกอิน';

-- -----------------------------------------------------------------------------
-- 1) profiles — โปรไฟล์พนักงานที่ซิงค์มาจาก Auth0
-- -----------------------------------------------------------------------------
create table if not exists public.profiles (
  id            text primary key,                    -- Auth0 sub เช่น 'auth0|677a...'
  email         text not null unique,
  full_name     text,
  avatar_url    text,
  role          text not null default 'user'
                  check (role in ('user', 'admin')),
  department    text,
  is_active     boolean not null default true,
  last_login_at timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists profiles_email_idx on public.profiles (lower(email));
create index if not exists profiles_role_idx  on public.profiles (role) where role = 'admin';

-- -----------------------------------------------------------------------------
-- 2) apps — ทะเบียนแอปที่แสดงบนหน้า Portal  ★ เพิ่มแอปใหม่ได้จากหน้า Admin
-- -----------------------------------------------------------------------------
create table if not exists public.apps (
  id             bigint generated by default as identity primary key,
  slug           text not null unique,               -- ใช้อ้างอิงในโค้ด เช่น 'erp'
  name           text not null,
  description    text,
  category       text not null default 'ทั่วไป',

  -- ★ แกนหลัก: แอปนี้อยู่ฝั่งไหน
  network        text not null default 'internet'
                   check (network in ('internet', 'intranet')),

  url            text not null,                      -- ปลายทางเมื่อคลิก
  sso_url        text,                               -- ถ้ามี = ใช้ URL นี้แทน url เพื่อเข้าผ่าน SSO
  health_url     text,                               -- endpoint สำหรับ probe (เช่น .../ping.php)

  icon           text not null default '🗂️',         -- emoji หรือชื่อไอคอน
  accent         text not null default 'slate'
                   check (accent in ('slate','blue','emerald','amber','rose','violet','cyan','orange')),

  open_in_new_tab boolean not null default true,
  allowed_roles   text[] not null default array['user','admin'],
  sort_order      integer not null default 100,
  is_active       boolean not null default true,

  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists apps_active_idx on public.apps (is_active, sort_order);

comment on column public.apps.network    is 'internet = เข้าได้จากทุกที่ / intranet = ต้องต่อ VPN';
comment on column public.apps.health_url is 'ถ้ากรอก ระบบจะ probe URL นี้เพื่อบอกสถานะออนไลน์บนการ์ด';
comment on column public.apps.sso_url    is 'URL ที่ทำ SSO handshake เช่น https://erp.local/auth-callback.php';

-- -----------------------------------------------------------------------------
-- 3) announcements — ประกาศข่าวสารภายในองค์กร
-- -----------------------------------------------------------------------------
create table if not exists public.announcements (
  id           bigint generated by default as identity primary key,
  title        text not null,
  content      text not null,
  category     text not null default 'General'
                 check (category in ('General', 'HR', 'IT Alert', 'Announcement')),
  is_pinned    boolean not null default false,
  published    boolean not null default true,
  published_at timestamptz not null default now(),
  author_id    text references public.profiles (id) on delete set null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists announcements_feed_idx
  on public.announcements (published, is_pinned desc, published_at desc);

-- -----------------------------------------------------------------------------
-- updated_at trigger
-- -----------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists profiles_touch      on public.profiles;
drop trigger if exists apps_touch          on public.apps;
drop trigger if exists announcements_touch on public.announcements;

create trigger profiles_touch      before update on public.profiles      for each row execute function public.touch_updated_at();
create trigger apps_touch          before update on public.apps          for each row execute function public.touch_updated_at();
create trigger announcements_touch before update on public.announcements for each row execute function public.touch_updated_at();

-- -----------------------------------------------------------------------------
-- is_admin() — SECURITY DEFINER เพื่อเลี่ยง RLS recursion บนตาราง profiles
-- -----------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = public.auth0_sub()
      and p.role = 'admin'
      and p.is_active
  );
$$;

-- -----------------------------------------------------------------------------
-- current_role_name() — role ของ user ปัจจุบัน (ใช้เช็ก allowed_roles)
-- -----------------------------------------------------------------------------
create or replace function public.current_role_name()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select p.role from public.profiles p where p.id = public.auth0_sub() and p.is_active),
    'user'
  );
$$;

-- =============================================================================
-- RLS
-- =============================================================================
alter table public.profiles      enable row level security;
alter table public.apps          enable row level security;
alter table public.announcements enable row level security;

-- ---- profiles ---------------------------------------------------------------
drop policy if exists profiles_select_self  on public.profiles;
drop policy if exists profiles_select_admin on public.profiles;
drop policy if exists profiles_update_self  on public.profiles;
drop policy if exists profiles_admin_all    on public.profiles;

create policy profiles_select_self on public.profiles
  for select to authenticated
  using (id = public.auth0_sub());

create policy profiles_select_admin on public.profiles
  for select to authenticated
  using (public.is_admin());

-- แก้ได้เฉพาะแถวตัวเอง (role/is_active ถูกล็อกไว้ด้วย trigger ด้านล่าง)
create policy profiles_update_self on public.profiles
  for update to authenticated
  using (id = public.auth0_sub())
  with check (id = public.auth0_sub());

create policy profiles_admin_all on public.profiles
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- กันผู้ใช้ทั่วไปยกระดับตัวเองเป็น admin ผ่าน policy update_self
create or replace function public.guard_profile_privileges()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_admin() then
    return new;
  end if;

  -- ผู้ใช้ทั่วไปห้ามเปลี่ยนสิทธิ์ สถานะ หรือรหัสประจำตัวของตัวเอง
  new.role      := old.role;
  new.is_active := old.is_active;
  new.id        := old.id;

  -- อีเมลเปลี่ยนได้เฉพาะเมื่อค่าใหม่ตรงกับอีเมลใน JWT
  -- (เส้นทางเดียวที่ทำได้คือ RPC sync_profile ซึ่งอ่านค่าจากโทเคนเอง)
  -- ถ้าไม่มีเงื่อนไขนี้ อีเมลที่เปลี่ยนใน Auth0 จะไม่มีวันซิงค์ลงตารางนี้ได้เลย
  if new.email is distinct from old.email
     and lower(new.email) is distinct from lower(coalesce(auth.jwt() ->> 'email', '')) then
    new.email := old.email;
  end if;

  return new;
end;
$$;

drop trigger if exists profiles_guard on public.profiles;
create trigger profiles_guard
  before update on public.profiles
  for each row execute function public.guard_profile_privileges();

-- ---- apps -------------------------------------------------------------------
drop policy if exists apps_select_visible on public.apps;
drop policy if exists apps_admin_all      on public.apps;

create policy apps_select_visible on public.apps
  for select to authenticated
  using (
    is_active
    and public.auth0_sub() is not null
    and public.current_role_name() = any (allowed_roles)
  );

create policy apps_admin_all on public.apps
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ---- announcements ----------------------------------------------------------
drop policy if exists announcements_select_published on public.announcements;
drop policy if exists announcements_admin_all        on public.announcements;

create policy announcements_select_published on public.announcements
  for select to authenticated
  using (published and public.auth0_sub() is not null);

create policy announcements_admin_all on public.announcements
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- =============================================================================
-- RPC: sync_profile()
-- Client ไม่ต้องส่ง id/email เอง — อ่านจาก JWT ทั้งหมด กัน spoofing
-- =============================================================================
create or replace function public.sync_profile(
  p_full_name  text default null,
  p_avatar_url text default null
)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sub    text := public.auth0_sub();
  v_email  text := coalesce(auth.jwt() ->> 'email', auth.jwt() -> 'user_metadata' ->> 'email');
  v_result public.profiles;
begin
  if v_sub is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;
  if v_email is null then
    raise exception 'JWT ไม่มี claim email — ตรวจสอบ Auth0 Post-Login Action' using errcode = '22023';
  end if;

  insert into public.profiles as p (id, email, full_name, avatar_url, last_login_at)
  values (v_sub, lower(v_email), p_full_name, p_avatar_url, now())
  on conflict (id) do update
    set email         = excluded.email,
        full_name     = coalesce(excluded.full_name, p.full_name),
        avatar_url    = coalesce(excluded.avatar_url, p.avatar_url),
        last_login_at = now()
  returning * into v_result;

  if not v_result.is_active then
    raise exception 'บัญชีนี้ถูกระงับการใช้งาน' using errcode = '28000';
  end if;

  return v_result;
end;
$$;

revoke all on function public.sync_profile(text, text) from public;
grant execute on function public.sync_profile(text, text) to authenticated;

-- =============================================================================
-- Grants
-- =============================================================================
-- สิทธิ์ระดับตารางเปิดกว้าง แต่ RLS ด้านบนเป็นตัวตัดสินจริงว่าแถวไหนแตะได้
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.apps          to authenticated;
grant select, insert, update, delete on public.announcements to authenticated;
grant select, update                 on public.profiles      to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- anon ไม่ควรเห็นอะไรเลย
revoke all on public.profiles      from anon;
revoke all on public.apps          from anon;
revoke all on public.announcements from anon;
